# Generated by Django 6.0.3 on 2026-03-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apartment_is_approved_apartment_total_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extra_description',
            field=models.TextField(blank=True, help_text="Additional content like 'Incredible Result'", null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True, help_text='Comma-separated features', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='land_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
