# Generated by Django 6.0.3 on 2026-03-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_extra_description_project_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='handover_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='orientation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='parking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
